portada:
    path: /{ciudad}
    defaults: 
        _controller: OfertaBundle:Default:portada
        ciudad: '%cupon.ciudad_por_defecto%'

_portada:
    path: /
    defaults: 
        _controller: FrameworkBundle:Redirect:redirect
        route: portada

pagina_estatica:
    path:  /sitio/{pagina}/
    defaults: 
        _controller: OfertaBundle:Sitio:estatica

ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }

oferta:
    path: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

ciudad_recientes:
    path: /{ciudad}/recientes
    defaults: { _controller: CiudadBundle:Default:recientes }

tienda_portada:
    path: /{ciudad}/tiendas/{tienda}
    defaults: { _controller: TiendaBundle:Default:portada }

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /