portada:
    path: /{_locale}/{ciudad}
    defaults: 
        _controller: OfertaBundle:Default:portada
        ciudad: '%cupon.ciudad_por_defecto%'
        _locale: es

_portada:
    path: /
    defaults: 
        _controller: FrameworkBundle:Redirect:redirect
        route: portada

pagina_estatica:
    path:  /{_locale}/sitio/{pagina}/
    defaults: 
        _controller: OfertaBundle:Sitio:estatica

ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }

oferta:
    path: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

ciudad_recientes:
    path: /{ciudad}/recientes.{_format}
    defaults: { _controller: CiudadBundle:Default:recientes, _format: html }
    requirements:
        _format: html|rss

tienda_portada:
    path: /{ciudad}/tiendas/{tienda}
    defaults: { _controller: TiendaBundle:Default:portada }

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix: /{_locale}/usuario

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix: /{_locale}

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: en|es

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix: /{_locale}