<?php

namespace Cupon\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
public function findTodasLasCompras($usuario)
{
	$em = $this->getEntityManager();
	$dql = 'SELECT v, o, t
			  FROM OfertaBundle:Venta v
			  JOIN v.oferta o
			  JOIN o.tienda t
			 WHERE v.usuario = :id
		  ORDER BY v.fecha DESC';

	$consulta = $em->createQuery($dql);
	$consulta->setParameter('id', $usuario);
	
	return $consulta->getResult();
	}
}
